### ISSUE TITLE
Authorization middleware

### ISSUE THREAD

**Issue by Oxygend** [go-playground/lars#14]
Hi, it isn't really an issue but more a question.

I want to create  a middleware which check the api key and if the api key is not valid then request does not go any further.

For example, request is http://example.com/accounts?api_key=xxx
It goes thru the middleware of /accounts group and it seems like api_key is not valid. How do I reject the request at the stage of it going thru the middleware?

**Comment by joeybloggs** [comment]
Hey @Oxygend 

If you want to stop the request right there then do your http.Error(...) and return without calling the c.Next()
eg. https://github.com/go-playground/lars/blob/master/middleware/gzip.go#L84 if next isn't called the middleware stops.

If your using other middleware like the STD lib compatible then the http.Error(...) And return will also work as the response code is checked and if not 200 then stops.

Let me know if this helps :)

**Comment by Oxygend** [comment]
Thanks!
