### ISSUE TITLE
/user/100/   match  l.Get("/user/:id"

### ISSUE THREAD

**Issue by tablecell** [go-playground/lars#22]
http://localhost:3007/user/    404 
http://localhost:3007/user/100    right
http://localhost:3007/user/100/   expect 404 but match  "/user/:id"

**Comment by deankarn** [comment]
@tablecell Lars sets a series of sane defaults upon creation which includes redirecting upon a non-matching trailing slash.

If you use curl -v ... you should see the redirect request. This can be turned off if desired.
